Raised version of CMake when recent version of Boost is used to fix CMake warnings

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -51,7 +51,7 @@ matrix:
     # GCC 7, Boost 1.70.0, Qt 5.x.
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=gcc C_COMPILER=gcc-7 CXX_COMPILER=g++-7 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
+      env: CXX_COMPILER_FAMILY=gcc C_COMPILER=gcc-7 CXX_COMPILER=g++-7 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
       compiler: gcc
       addons: &apt-gcc7-boost170-qt5
         apt:
@@ -67,13 +67,13 @@ matrix:
           sources: *gcc-package-sources
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=gcc C_COMPILER=gcc-7 CXX_COMPILER=g++-7 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
+      env: CXX_COMPILER_FAMILY=gcc C_COMPILER=gcc-7 CXX_COMPILER=g++-7 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
       compiler: gcc
       addons: *apt-gcc7-boost170-qt5
     # Clang 8.0, Boost 1.70.0, Qt 5.x
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-8 CXX_COMPILER=clang++-8 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
+      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-8 CXX_COMPILER=clang++-8 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
       compiler: clang
       addons: &apt-clang80-boost170-qt5
         apt:
@@ -91,13 +91,13 @@ matrix:
             - sourceline: 'ppa:mhier/libboost-latest'
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-8 CXX_COMPILER=clang++-8 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
+      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-8 CXX_COMPILER=clang++-8 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
       compiler: clang
       addons: *apt-clang80-boost170-qt5
     # Clang 7.0, Boost 1.70.0, Qt 5.x
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-7 CXX_COMPILER=clang++-7 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
+      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-7 CXX_COMPILER=clang++-7 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
       compiler: clang
       addons: &apt-clang70-boost170-qt5
         apt:
@@ -115,13 +115,13 @@ matrix:
             - sourceline: 'ppa:mhier/libboost-latest'
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-7 CXX_COMPILER=clang++-7 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
+      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-7 CXX_COMPILER=clang++-7 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
       compiler: clang
       addons: *apt-clang70-boost170-qt5
     # Clang 6.0, Boost 1.70.0, Qt 5.x
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-6.0 CXX_COMPILER=clang++-6.0 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
+      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-6.0 CXX_COMPILER=clang++-6.0 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
       compiler: clang
       addons: &apt-clang60-boost170-qt5
         apt:
@@ -139,13 +139,13 @@ matrix:
             - sourceline: 'ppa:mhier/libboost-latest'
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-6.0 CXX_COMPILER=clang++-6.0 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
+      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-6.0 CXX_COMPILER=clang++-6.0 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
       compiler: clang
       addons: *apt-clang60-boost170-qt5
     # Clang 5.0, Boost 1.68.0, Qt 5.x
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 BOOST_VERSION=1.68.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
+      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.68.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
       compiler: clang
       addons: &apt-clang50-boost168-qt5
         apt:
@@ -163,10 +163,10 @@ matrix:
             - sourceline: 'ppa:mhier/libboost-latest'
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 BOOST_VERSION=1.68.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
+      env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.68.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
       compiler: clang
       addons: *apt-clang50-boost168-qt5
-    # MacOS, Clang Apple LLVM version 10.0.1, Boost 1.69.0, Qt 5.x
+    # MacOS, Clang Apple LLVM version 10.0.1, Boost 1.70.0, Qt 5.x
     - os: osx
       osx_image: xcode10.2
       env: CXX_COMPILER_FAMILY=clang C_COMPILER=clang CXX_COMPILER=clang++ BOOST_VERSION=1.70.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
@@ -186,7 +186,7 @@ matrix:
     # GCC 7, Boost 1.68.0, Qt 5.x.
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=gcc C_COMPILER=gcc-7 CXX_COMPILER=g++-7 BOOST_VERSION=1.68.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
+      env: CXX_COMPILER_FAMILY=gcc C_COMPILER=gcc-7 CXX_COMPILER=g++-7 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.68.0 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
       compiler: gcc
       addons: &apt-gcc7-boost168-qt5
         apt:
@@ -202,7 +202,7 @@ matrix:
           sources: *gcc-package-sources
     - os: linux
       dist: trusty
-      env: CXX_COMPILER_FAMILY=gcc C_COMPILER=gcc-7 CXX_COMPILER=g++-7 BOOST_VERSION=1.68.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
+      env: CXX_COMPILER_FAMILY=gcc C_COMPILER=gcc-7 CXX_COMPILER=g++-7 CMAKE_VERSION=3.15.1 BOOST_VERSION=1.68.0 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
       compiler: gcc
       addons: *apt-gcc7-boost168-qt5
     # GCC 7, Boost 1.55.0, Qt 5.x
@@ -684,6 +684,42 @@ install:
   - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
       export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:${PATH}";
     fi
+  - export DETECTED_CMAKE_VERSION="$(cmake --version | sed -r 's/cmake version ([0-9]+\.[0-9]+\.[0-9]+)/\1/;t;d')"
+  - echo "Detected CMake of ${DETECTED_CMAKE_VERSION} version"
+  - if [[ ! -z "${CMAKE_VERSION+x}" ]]; then
+      echo "CMake of ${CMAKE_VERSION} version is requested" &&
+      if [[ "${CMAKE_VERSION}" != "${DETECTED_CMAKE_VERSION}" ]]; then
+        if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
+          cmake_archive_base_name="cmake-${CMAKE_VERSION}-Linux-x86_64" &&
+          cmake_home="${DEPENDENCIES_HOME}/${cmake_archive_base_name}" &&
+          if [[ -d "${cmake_home}" ]]; then
+            echo "CMake ${CMAKE_VERSION} found at ${cmake_home}";
+          else
+            echo "CMake ${CMAKE_VERSION} not found at ${cmake_home}" &&
+            cmake_archive_name="${cmake_archive_base_name}.tar.gz" &&
+            cmake_archive_file="${DOWNLOADS_HOME}/${cmake_archive_name}" &&
+            cmake_download_url="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${cmake_archive_name}" &&
+            if [[ -f "${cmake_archive_file}" ]]; then
+              echo "CMake ${CMAKE_VERSION} archive found at ${cmake_archive_file}";
+            else
+              echo "CMake ${CMAKE_VERSION} archive not found at ${cmake_archive_file}" &&
+              echo "Going to download CMake ${CMAKE_VERSION} archive from ${boost_download_url} to ${cmake_archive_file}" &&
+              mkdir -p "${DOWNLOADS_HOME}" &&
+              curl --connect-timeout "${CURL_CONNECT_TIMEOUT}" --max-time "${CURL_MAX_TIME}" --retry "${CURL_RETRY}" --retry-delay "${CURL_RETRY_DELAY}" -jksSL "${cmake_download_url}" --output "${cmake_archive_file}" &&
+              echo "Download of CMake ${CMAKE_VERSION} archive from ${cmake_download_url} to ${cmake_archive_file} completed successfully";
+            fi &&
+            mkdir -p "${DEPENDENCIES_HOME}" &&
+            echo "Going to unpack CMake ${CMAKE_VERSION} archive from ${cmake_archive_file} to ${DEPENDENCIES_HOME}" &&
+            tar -xzf "${cmake_archive_file}" -C "${DEPENDENCIES_HOME}" &&
+            echo "Unpacking of CMake ${CMAKE_VERSION} archive from ${cmake_archive_file} to ${DEPENDENCIES_HOME} completed successfully";
+          fi &&
+          echo "CMake ${CMAKE_VERSION} is located at ${cmake_home}" &&
+          export PATH="${cmake_home}/bin:${PATH}";
+        else
+          echo "Custom version of CMake - ${CMAKE_VERSION} - is not supported for ${TRAVIS_OS_NAME} OS" &&
+          exit 1;
+        fi
+      fi
   - export PRE_INSTALLED_BOOST=0
   - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
       if [[ "${TRAVIS_DIST}" == "trusty" ]]; then
